export const API_ROUTES = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    GOOGLE: "/auth/google",
    GOOGLE_ROLE: "/auth/google/role",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    ADMIN: {
      LOGIN: "/admin/login",
      VERIFY_OTP: "/admin/verify-otp",
      LOGOUT: "/admin/logout",
    },
  },
  CUSTOMER: {
    PROFILE: "/customer/profile",
    AVATAR: "/customer/avatar",
    COVER: "/customer/cover",
    VERIFY: "/customer/verify",
    VERIFY_CONFIRM: "/customer/verify/confirm",
    VERIFICATION_STATUS: "/customer/verification-status",
  },
  TECHNICIAN: {
    PROFILE: "/technician/profile",
    AVATAR: "/technician/avatar",
    COVER: "/technician/cover",
    SKILLS: "/technician/skills",
    VERIFY: "/technician/verify",
    VERIFICATION_STATUS: "/technician/verification-status",
  },
  JOBS: {
    BASE: "/jobs",
    CATEGORIES: "/jobs/categories",
    DETAIL: (id: string) => `/jobs/${id}`,
    MINE: "/jobs/mine",
    COMPLETE: (id: string) => `/jobs/${id}/complete`,
    CANCEL: (id: string) => `/jobs/${id}/cancel`,
    APPLY: (id: string) => `/jobs/${id}/apply`,
    APPLICATIONS: (id: string) => `/jobs/${id}/applications`,
  },
  APPLICATIONS: {
    MINE: "/applications/mine",
    ACCEPT: (id: string) => `/applications/${id}/accept`,
    REJECT: (id: string) => `/applications/${id}/reject`,
  },
  REVIEWS: {
    BASE: "/reviews",
    USER: (id: string) => `/reviews/user/${id}`,
    JOB: (id: string) => `/reviews/job/${id}`,
  },
  CHAT: {
    SEND: "/chat/send",
    MESSAGES: (jobId: string, userId: string) => `/chat/${jobId}/${userId}`,
    CONVERSATIONS: "/chat/conversations",
    MARK_READ: (jobId: string) => `/chat/${jobId}/read`,
    UNREAD_COUNT: "/chat/unread-count",
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    UNREAD: "/notifications/unread",
    COUNT: "/notifications/count",
    READ_ALL: "/notifications/read-all",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    DELETE: (id: string) => `/notifications/${id}`,
  },
  PAYMENTS: {
    CALLBACK: "/payment/callback",
  },
  PUBLIC: {
    TOP_TECHNICIANS: "/public/top-technicians",
    RECENT_JOBS: "/public/recent-jobs",
    HIGH_PRICE_JOBS: "/public/high-price-jobs",
    STATS: "/public/stats",
    TECHNICIAN: (id: string) => `/public/technicians/${id}`,
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    USER_ACTIVATE: (id: string) => `/admin/users/${id}/activate`,
    USER_DEACTIVATE: (id: string) => `/admin/users/${id}/deactivate`,
    VERIFICATIONS_PENDING: "/admin/verifications/pending",
    VERIFICATIONS_APPROVE: "/admin/verifications/approve",
    VERIFICATIONS_REJECT: "/admin/verifications/reject",
    SETTINGS_FEES: "/admin/settings/fees",
    ANALYTICS: "/admin/analytics",
  },
} as const;